Homework 1
================
Mingee Choi
09/24/2022

# Problem 1

To find basic description of dataset:

``` r
data("penguins", package = "palmerpenguins")
summary(penguins)
```

    ##       species          island    bill_length_mm  bill_depth_mm  
    ##  Adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  
    ##  Chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  
    ##  Gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  
    ##                                  Mean   :43.92   Mean   :17.15  
    ##                                  3rd Qu.:48.50   3rd Qu.:18.70  
    ##                                  Max.   :59.60   Max.   :21.50  
    ##                                  NA's   :2       NA's   :2      
    ##  flipper_length_mm  body_mass_g       sex           year     
    ##  Min.   :172.0     Min.   :2700   female:165   Min.   :2007  
    ##  1st Qu.:190.0     1st Qu.:3550   male  :168   1st Qu.:2007  
    ##  Median :197.0     Median :4050   NA's  : 11   Median :2008  
    ##  Mean   :200.9     Mean   :4202                Mean   :2008  
    ##  3rd Qu.:213.0     3rd Qu.:4750                3rd Qu.:2009  
    ##  Max.   :231.0     Max.   :6300                Max.   :2009  
    ##  NA's   :2         NA's   :2

To find size of the dataset (nrow and ncol):

``` r
x=data.frame(penguins)
y=data.frame(penguins)
nrow(x)
```

    ## [1] 344

``` r
ncol(y)
```

    ## [1] 8

**Description of dataset:** *variable names: species, island,
bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g, sex, and
year *Values of important variables: *Sex: female=165, male=168
*Species: Adelie=152, Chinstrap=68, Gentoo=124 *Island: Biscoe=168,
Dream=124, Torgersen=52 *Means: Bill Length (mm)=43.92, Bill Depth
(mm)=17.15, Body Mass (g)=4202 *Median: Bill Length (mm)=44.45, Bill
Depth (mm)=17.30, Body Mass (g)=4050 *Rows=334 and Columns=8 \*Mean
flipper length:200.9

\####Scatterplot of flipper length vs bill length To make scatterplot
with species in different colors:

``` r
library(tidyverse)
ggplot(penguins, aes(x=flipper_length_mm, y=bill_length_mm))+geom_point(aes(color=species))
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](p8105_hw1_mlc2287_files/figure-gfm/plot_problem2-1.png)<!-- -->

``` r
ggsave("scatter_plot.pdf")
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

# Problem 2

Creating a dataframe

``` r
problem2_df = tibble(
  a=rnorm(n=10),
  result <- a>0,
  vec_char = c("Here", "Is", "A", "Character", "Vector", "For", "Homework", "1", "Problem", "2"),
  vec_factor = factor(c(1,2,3,1,2,3,1,2,3,1)),
)
  problem2_df
```

    ## # A tibble: 10 × 4
    ##          a `result <- a > 0` vec_char  vec_factor
    ##      <dbl> <lgl>             <chr>     <fct>     
    ##  1 -0.698  FALSE             Here      1         
    ##  2  0.975  TRUE              Is        2         
    ##  3 -0.0973 FALSE             A         3         
    ##  4  0.219  TRUE              Character 1         
    ##  5 -0.323  FALSE             Vector    2         
    ##  6  0.965  TRUE              For       3         
    ##  7  0.0859 TRUE              Homework  1         
    ##  8  0.154  TRUE              1         2         
    ##  9 -1.31   FALSE             Problem   3         
    ## 10 -0.420  FALSE             2         1
